version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      python-dependencies:
        patterns: ["*"]

  # Enable version updates for cargo
  - package-ecosystem: "cargo"
    directory: "/rust_scraper"
    schedule:
      interval: "daily"
    groups:
      rust-dependencies:
        patterns: ["*"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns: ["*"]
