[package]
name = "rust_scraper"
version = "0.6.0"
edition = "2021"

[lib]
name = "rust_scraper"
crate-type = ["cdylib"]

[dependencies]
scraper = "0.19.0"
pyo3 = { version = "0.24.1", features = ["extension-module"] }
rayon = "1.10.0"
ureq = { version = "2.9.6", features = ["json"] }
