[package]
name = "rust_scraper"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_scraper"
crate-type = ["cdylib"]

[dependencies]
ureq = "2.9.6"
scraper = "0.19.0"
pyo3 = { version = "0.20.0", features = ["extension-module"] }
